// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_rpg.domain.Data;

#nullable disable

namespace dotnet_rpg.domain.Migrations
{
    [DbContext(typeof(EmployeeManagerDbContext))]
    [Migration("20231223074719_addedOrdersandRefershtokenObjects")]
    partial class addedOrdersandRefershtokenObjects
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dotnet_rpg.domain.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "IT"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Control"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HR"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("dotnet_rpg.domain.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeveloper")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 2,
                            FirstName = "Adeola",
                            Gender = "Male",
                            IsDeveloper = false,
                            LastName = "Malian",
                            Salary = 61000.0,
                            State = "Ogun"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 3,
                            FirstName = "Olaolu",
                            Gender = "FeMale",
                            IsDeveloper = true,
                            LastName = "Mapayi",
                            Salary = 3400.0,
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 4,
                            FirstName = "Deji",
                            Gender = "FeMale",
                            IsDeveloper = false,
                            LastName = "Henry",
                            Salary = 8900.0,
                            State = "Oyo"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            FirstName = "Sheyi",
                            Gender = "Male",
                            IsDeveloper = true,
                            LastName = "Alao",
                            Salary = 7890.0,
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            FirstName = "Opeola",
                            Gender = "FeMale",
                            IsDeveloper = false,
                            LastName = "Bayo",
                            Salary = 8600.0,
                            State = "Oyo"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            FirstName = "Adeola",
                            Gender = "Male",
                            IsDeveloper = false,
                            LastName = "Malian",
                            Salary = 61000.0,
                            State = "Ogun"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            FirstName = "Olaolu",
                            Gender = "FeMale",
                            IsDeveloper = true,
                            LastName = "Mapayi",
                            Salary = 3400.0,
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 4,
                            FirstName = "Deji",
                            Gender = "FeMale",
                            IsDeveloper = false,
                            LastName = "Henry",
                            Salary = 9900.0,
                            State = "Oyo"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 1,
                            FirstName = "Sheyi",
                            Gender = "Male",
                            IsDeveloper = true,
                            LastName = "Alao",
                            Salary = 7890.0,
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 5,
                            FirstName = "Opeola",
                            Gender = "FeMale",
                            IsDeveloper = false,
                            LastName = "Bayo",
                            Salary = 9600.0,
                            State = "Oyo"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 2,
                            FirstName = "Adeola",
                            Gender = "Male",
                            IsDeveloper = false,
                            LastName = "Malian",
                            Salary = 61000.0,
                            State = "Ogun"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 3,
                            FirstName = "Olaolu",
                            Gender = "FeMale",
                            IsDeveloper = true,
                            LastName = "Mapayi",
                            Salary = 3400.0,
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 4,
                            FirstName = "Deji",
                            Gender = "FeMale",
                            IsDeveloper = false,
                            LastName = "Henry",
                            Salary = 8900.0,
                            State = "Oyo"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 1,
                            FirstName = "Sheyi",
                            Gender = "Male",
                            IsDeveloper = true,
                            LastName = "Alao",
                            Salary = 7890.0,
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 5,
                            FirstName = "Opeola",
                            Gender = "FeMale",
                            IsDeveloper = false,
                            LastName = "Bayo",
                            Salary = 8600.0,
                            State = "Oyo"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 2,
                            FirstName = "Adeola",
                            Gender = "Male",
                            IsDeveloper = false,
                            LastName = "Malian",
                            Salary = 61000.0,
                            State = "Ogun"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 3,
                            FirstName = "Olaolu",
                            Gender = "FeMale",
                            IsDeveloper = true,
                            LastName = "Mapayi",
                            Salary = 3400.0,
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 4,
                            FirstName = "Deji",
                            Gender = "FeMale",
                            IsDeveloper = false,
                            LastName = "Henry",
                            Salary = 9900.0,
                            State = "Oyo"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 1,
                            FirstName = "Sheyi",
                            Gender = "Male",
                            IsDeveloper = true,
                            LastName = "Alao",
                            Salary = 7890.0,
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 5,
                            FirstName = "Opeola",
                            Gender = "FeMale",
                            IsDeveloper = false,
                            LastName = "Bayo",
                            Salary = 9600.0,
                            State = "Oyo"
                        });
                });

            modelBuilder.Entity("dotnet_rpg.domain.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsersId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("dotnet_rpg.domain.Models.RefereshTokenModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpired")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsersId");

                    b.ToTable("RefereshTokens");
                });

            modelBuilder.Entity("dotnet_rpg.domain.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dotnet_rpg.domain.Models.Employee", b =>
                {
                    b.HasOne("dotnet_rpg.domain.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("dotnet_rpg.domain.Models.Order", b =>
                {
                    b.HasOne("dotnet_rpg.domain.Models.Users", "Users")
                        .WithMany("Orders")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("dotnet_rpg.domain.Models.RefereshTokenModels", b =>
                {
                    b.HasOne("dotnet_rpg.domain.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("dotnet_rpg.domain.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("dotnet_rpg.domain.Models.Users", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
